apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-demo
  labels:
    app: flappy-bird:22
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flappy-bird:22
  template:
    metadata:
      labels:
        app: flappy-bird:22
    spec:
      containers:
      - name: flappy-bird:22
        image: sontungbk85/flappy-bird:22
        ports:
        - containerPort: 5100
---
apiVersion: v1
kind: Service
metadata:
  name: game-demo
spec:
  selector:
    app.kubernetes.io/name: flappy-bird:22
  ports:
  - protocol: TCP
    port: 80
    targetPort: 32001