apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-demo
  labels:
    app: flappybird
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flappybird
  template:
    metadata:
      labels:
        app: flappybird
    spec:
      containers:
      - name: flappybird
        image: sontungbk85/flappy-bird:40
        ports:
        - containerPort: 5100
---
apiVersion: v1
kind: Service
metadata:
  name: game-demo
spec:
  selector:
    app.kubernetes.io/name: flappybird
  ports:
  - protocol: TCP
    port: 80
    targetPort: 32001
